MediterraneanDreamBoats/Medit1/Models/ViewModels/AdministrationViewModel.cs
using System.Collections.Generic;

namespace Medit1.Models.ViewModels
{
    public class AdministrationViewModel
    {
        public ICollection<Port> Ports { get; set; }
        public ICollection<Boat> Boats { get; set; }
        public ICollection<Cruise> Cruises { get; set; }
    }
}

MediterraneanDreamBoats/Medit1/Controllers/AdministrationController.cs
using System.Threading.Tasks;
using Medit1.Models;
using Medit1.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Medit1.Controllers
{
    [Authorize(Roles = "Director")]
    public class AdministrationController : Controller
    {
        private readonly Medit1DbContext _context;

        public AdministrationController(Medit1DbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var administrationViewModel = new AdministrationViewModel
            {
                Boats = await _context.Boats.ToListAsync(),
                Cruises = await _context.Cruises.ToListAsync(),
                Ports = await _context.Ports.ToListAsync()
            };
            return View(administrationViewModel);
        }
    }
}

MediterraneanDreamBoats/Medit1/Controllers/BoatsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Medit1.Models;
using Microsoft.AspNetCore.Authorization;


namespace Medit1.Controllers
{
    [Authorize]
    public class BoatsController : Controller
    {
        private readonly Medit1DbContext _context;

        public BoatsController(Medit1DbContext context)
        {
            _context = context;
        }



        // GET: Boats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Type,NbConvives")] Boat boat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boat);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Administration");
            }
            return View(boat);
        }

        // GET: Boats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boats.FindAsync(id);
            if (boat == null)
            {
                return NotFound();
            }
            return View(boat);
        }

        // POST: Boats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BoatId,Name,Description,Type,NbConvives")] Boat boat)
        {
            if (id != boat.BoatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoatExists(boat.BoatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Administration");
            }
            return View(boat);
        }

        // GET: Boats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boats
                .FirstOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }

        // POST: Boats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var boat = await _context.Boats.FindAsync(id);
            _context.Boats.Remove(boat);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Administration");
        }

        private bool BoatExists(int id)
        {
            return _context.Boats.Any(e => e.BoatId == id);
        }
        // GET: Boats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boats
                .FirstOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }


    }
}

MediterraneanDreamBoats/Medit1/Controllers/PortsController.cs
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Medit1.Models;
using Medit1.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Medit1.Controllers
{
    [Authorize]
    public class PortsController : Controller
    {
        private readonly Medit1DbContext _context;

        public PortsController(Medit1DbContext context)
        {
            _context = context;
        }

        


        // GET: Ports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PortViewModel portVm)
        {
            if (ModelState.IsValid)
            {
                var port = new Port()
                {
                    Latitude = float.Parse(portVm.Latitude),
                    Longitude = float.Parse(portVm.Longitude),
                    Name = portVm.Name
                };
                _context.Add(port);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Administration");
            }
            return View(portVm);
        }

        // GET: Ports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var port = await _context.Ports.FindAsync(id);
            if (port == null)
            {
                return NotFound();
            }

            var portVm = new PortViewModel()
            {
                Latitude = port.Latitude.ToString(CultureInfo.CurrentCulture),
                Longitude = port.Longitude.ToString(CultureInfo.CurrentCulture),
                Name = port.Name,
                PortId = port.PortId
            };

            return View(portVm);
        }

        // POST: Ports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PortViewModel portViewModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var port = new Port()
                    {
                        Latitude = float.Parse(portViewModel.Latitude),
                        Longitude = float.Parse(portViewModel.Longitude),
                        Name = portViewModel.Name,
                        PortId = portViewModel.PortId
                    };

                    _context.Update(port);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortExists(portViewModel.PortId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Administration");
            }
            return View(portViewModel);
        }

        // GET: Ports/Delete/5
        public async Task<IActionResult> Delete(int? id, [AllowNull]ICollection<string> cruisesName)
        {
            if (id == null)
            {
                return NotFound();
            }

            var port = await _context.Ports
                .FirstOrDefaultAsync(m => m.PortId == id);
            if (port == null)
            {
                return NotFound();
            }
            var portvm = new DeletePortViewModel()
            {
                CruisesName = cruisesName,
                Latitude = port.Latitude,
                Longitude = port.Longitude,
                Name = port.Name,
                PortId = port.PortId
            };


            return View(portvm);
        }

        // POST: Ports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var port = await _context.Ports.FindAsync(id);
            if (port == null) return NotFound();
            var cruises = await _context.Cruises.Where(c => c.PortDepart.PortId == id || c.ArrivalPort.PortId == id).ToListAsync();
            var cruisesTrans = await _context.Cruises.Include(c => c.TransitPorts).Where(c => c.TransitPorts.Any(t => t.PortId == id))
                .ToListAsync();
            var enumerable = cruises.Concat(cruisesTrans).ToList();
            if (enumerable.Count==0)
            {
                _context.Ports.Remove(port);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Administration");
            }
            else
            {
                var cruisesName = new HashSet<string>();
                foreach (var cruise in enumerable)
                {
                    cruisesName.Add(cruise.Name);
                }

                return RedirectToAction("Delete", new { id = id ,cruisesName=cruisesName});

            }

        }

        private bool PortExists(int id)
        {
            return _context.Ports.Any(e => e.PortId == id);
        }
    }
}

MediterraneanDreamBoats/Medit1/Views/Administration/Index.cshtml
@model Medit1.Models.ViewModels.AdministrationViewModel

@{
    ViewBag.Title = "Panel d'administration";
    Layout = "_Layout";
}

<h1>Panel D'Administration</h1>

<div class="container border border-secondary" id="port">
    <div class="d-flex">
        <h2 class="p-2">Port</h2>
        <a class="btn btn-primary ml-auto p-2"  asp-controller="Ports" asp-action="Create">Ajouter un port</a>
    </div>
    <div class="table-responsive">
        <table class="table table-fixed">
            <thead>
                <tr>
                    <th scope="col" class="col-3">Nom</th>
                    <th scope="col" class="col-3">Lattitude</th>
                    <th scope="col" class="col-3">Longitude</th>
                    <th scope="col" class="col-3">Options</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var port in Model.Ports)
                    {
                        <tr class="d-flex justify-content-center">
                            <td class="col-3">@port.Name</td>
                            <td class="col-3">@port.Latitude</td>
                            <td class="col-3">@port.Longitude</td>
                            <td class="col-3">
                                <a class="btn btn-primary btn-sm" asp-route-id="@port.PortId" asp-controller="Ports" asp-action="Edit">Modifier</a>
                                <a class="btn btn-primary btn-sm" asp-route-id="@port.PortId" asp-controller="Ports" asp-action="Delete">Supprimer</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>

        </table>
    </div>
</div>
<div class="container border border-secondary" id="boat">
    <div class="d-flex">
        <h2 class="p-2">Bateau</h2>
        <a class="btn btn-primary ml-auto p-2"  asp-controller="Boats" asp-action="Create">Ajouter un bateau</a>
    </div>
    <div class="table-responsive">
        <table class="table table-fixed">
            <thead>
                <tr>
                    <th scope="col" class="col-3">Nom</th>
                    <th scope="col" class="col-3">Type</th>
                    <th scope="col" class="col-1">Places</th>
                    <th scope="col" class="col-4">Options</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var boat in Model.Boats)
                    {
                        <tr class="d-flex ">
                            <td class="col-3">@boat.Name</td>
                            <td class="col-3">@boat.Type</td>
                            <td class="col-1">@boat.NbConvives</td>
                            <td class="col-4">
                                <a class="btn btn-primary btn-sm" asp-route-id="@boat.BoatId" asp-controller="Boats" asp-action="Edit">Modifier</a>
                                <a class="btn btn-primary btn-sm" asp-route-id="@boat.BoatId" asp-controller="Boats" asp-action="Delete">Supprimer</a>
                                <a class="btn btn-primary btn-sm" asp-route-id="@boat.BoatId" asp-controller="Boats" asp-action="Details">Detail</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div class="container border border-secondary" id="cruises">
    <div class="d-flex">
        <h2 class="p-2">Croisière</h2>
        <a class="btn btn-primary ml-auto p-2" asp-area="" asp-controller="Cruises" asp-action="Create">Ajouter une Croisière</a>
    </div>
    <div class="table-responsive">
        <table class="table table-fixed">
            <thead>
                <tr>
                    <th scope="col" class="col-2">Nom</th>
                    <th scope="col" class="col-3">Départ</th>
                    <th scope="col" class="col-3">Arrivé</th>
                    <th scope="col" class="col-2">Bateau</th>
                    <th scope="col" class="col-2">Options</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var cruise in Model.Cruises)
                    {
                        <tr class="d-flex justify-content-center">
                            <td class="col-2">@cruise.Name</td>
                            <td class="col-3">@cruise.DateDepart.ToShortDateString() (@cruise.PortDepart.Name)</td>
                            <td class="col-3">@cruise.DateArrivee.ToShortDateString() (@cruise.ArrivalPort.Name)</td>
                            <td class="col-2">@cruise.Boat.Name</td>
                            <td class="col-2">
                                <a class="btn btn-primary btn-sm" asp-route-id="@cruise.CruiseId" asp-controller="Reservations" asp-action="AllReservationForCruise">Reservations</a>
                                <a class="btn btn-primary btn-sm" asp-route-id="@cruise.CruiseId" asp-controller="Cruises" asp-action="Delete">Supprimer</a>
                                <a class="btn btn-primary btn-sm" asp-route-id="@cruise.CruiseId" asp-controller="Cruises" asp-action="Details">Détail</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>