MediterraneanDreamBoats/Medit1/Controllers/AdministrationController.cs
using System.Threading.Tasks;
using Medit1.Models;
using Medit1.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Medit1.Controllers
{
    [Authorize(Roles = "Director")]
    public class AdministrationController : Controller
    {
        private readonly Medit1DbContext _context;

        public AdministrationController(Medit1DbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var administrationViewModel = new AdministrationViewModel
            {
                Boats = await _context.Boats.ToListAsync(),
                Cruises = await _context.Cruises.ToListAsync(),
                Ports = await _context.Ports.ToListAsync()
            };
            return View(administrationViewModel);
        }
    }
}

MediterraneanDreamBoats/Medit1/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Medit1.Models;
using Medit1.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Medit1.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly Medit1DbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;


        public ReservationsController(Medit1DbContext context, SignInManager<User> signInManager,
            UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [Authorize(Roles = "Director")]
        public async Task<IActionResult> AllReservationForCruise(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var cruise = await _context.Cruises.FirstAsync(c => c.CruiseId == id);
            var reservations = await _context.ParticipantReservations
                .Include(p=>p.Reservation)
                .Include(p=>p.Participant)
                .Where(r => r.Reservation.Cruise.CruiseId == cruise.CruiseId)
                .ToListAsync();
            var administrationReservationViewModel = new AdministrationReservationViewModel()
            {
                Cruise =  cruise,
                ParticipantReservations = reservations
            };
            return View(administrationReservationViewModel);
            
        }


        // GET: Reservations
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var reservations = await _context.Reservations
                .Include(r => r.Cruise)
                .Where(r => r.UserId == userId)
                .OrderBy(r => r.Cruise.CruiseId)
                .ToListAsync();

            return View(reservations);

        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var participants =  await _context.Participant.ToListAsync();
            var reservation = await _context.Reservations
                .Include(r=>r.Cruise).ThenInclude(c=>c.TypeCruise)
                .Include(r=>r.Participants)
                .Where(r=>r.UserId == userId)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public async Task<IActionResult> Create(int?id)
        {
            try
            {
                var cruise =  _context.Cruises
                    .Include(c=>c.Boat)
                    .Include(c=>c.PortDepart)
                    .Include(c=>c.ArrivalPort)
                    .Include(c=>c.TypeCruise)
                    .First(c => c.CruiseId == id);

                var allReservations =await _context.ParticipantReservations.Include(p => p.Reservation).ThenInclude(p => p.Cruise)
                    .Where(p => p.Reservation.Cruise.CruiseId == id).ToListAsync();

                var nbReservation = allReservations.Count;
                var nbTotalPlace = cruise.Boat.NbConvives;
                var placeDispo = nbTotalPlace - nbReservation;
                if (placeDispo == 0)
                {
                    return RedirectToAction("Index", "Home");
                }

                return View(new ReservationViewModel() { Cruise = cruise, PlaceRestante = placeDispo});
            }
            catch(Exception)
            {
                return RedirectToAction("Index", "Home");
            }

        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReservationViewModel reservationViewModel)
        {

            var cruise = await _context.Cruises.Include(c=>c.Boat).Include(c=>c.TypeCruise).FirstAsync(c => c.CruiseId == reservationViewModel.CruiseId);
            if (ModelState.IsValid)
            {
                var participants = reservationViewModel.Participants;
                var reservation = new Reservation(){Cruise = cruise};
                var usersReservations = new List<ParticipantReservation>();
                foreach (var participant in participants)
                {
                    if(!participant.Name.Equals("-1") && !participant.FirstName.Equals("-1"))
                        usersReservations.Add(new ParticipantReservation(){Reservation = reservation, Participant = participant});
                }

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                reservation.Participants = usersReservations;
                reservation.UserId = userId;
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            if (cruise != null)
            {
                var allReservations = await _context.ParticipantReservations.Include(p => p.Reservation).ThenInclude(p => p.Cruise)
                    .Where(p => p.Reservation.Cruise.CruiseId == cruise.CruiseId).ToListAsync();

                var nbReservation = allReservations.Count;
                int nbTotalPlace = cruise.Boat.NbConvives;
                int placeDispo = nbTotalPlace - nbReservation;
                reservationViewModel.Cruise = cruise;
                reservationViewModel.PlaceRestante = placeDispo-reservationViewModel.Participants.Count;
                return View(reservationViewModel);
            }
            return RedirectToAction("Index", "Home");
            
        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var participants = await _context.Participant.ToListAsync();
            var reservation = await _context.Reservations
                .Include(r => r.Cruise).ThenInclude(c => c.TypeCruise)
                .Include(r => r.Participants)
                .Where(r=>r.UserId==userId)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        [Produces("application/json")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editer()
        {
            var reservationId = int.Parse(HttpContext.Request.Query["reservationId"].ToString());
            var removed = HttpContext.Request.Query["removed"].ToArray();
            try
            {
                var userRes = await _context.ParticipantReservations.Where(p => p.ReservationId == reservationId)
                    .ToListAsync();
                foreach (var userReservation in userRes)
                {
                    if (removed.Contains(userReservation.ParticipantId.ToString()))
                    {
                        _context.ParticipantReservations.Remove(userReservation);
                        var participant = await _context.Participant
                            .Where(p => p.ParticipantId == userReservation.ParticipantId).FirstAsync();
                        _context.Participant.Remove(participant);
                    }
                }

                if (removed.Length == userRes.Count)
                {
                    var reservation = _context.Reservations.First(r => r.ReservationId == reservationId);
                    _context.Reservations.Remove(reservation);
                }

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ReservationExists(reservationId))
                {
                    return NotFound();
                }
            }

            return Json(new {redirectToUrl = Url.Action("Index")});
        }


        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.ReservationId == id);
        }
    }
}

MediterraneanDreamBoats/Medit1/Views/Cruises/Create.cshtml
@model Medit1.Models.ViewModels.CreateCruiseViewModel
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Csrf

@functions
{
    public string GetToken()
    {
        return Csrf.GetAndStoreTokens(Context).RequestToken;
    }
}


@{
    ViewData["Title"] = "Ajouter une croisière";
}

<input type="hidden" id="GetToken" name="GetToken" value="@GetToken()" />

<h1>Ajouter une croisière</h1>

<hr />
<div class="container-fluid">
    <div>
        <form asp-action="Create" enctype="multipart/form-data">
            
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cruise.Name" class="form-label"></label>
                <input asp-for="Cruise.Name" class="form-control" />
                <span asp-validation-for="Cruise.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cruise.Description" class="form-label"></label>
                <textarea asp-for="Cruise.Description" class="form-control"></textarea>
                <span asp-validation-for="Cruise.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cruise.TypeCruise" class="form-label"></label>
                <select asp-for="TypeCruiseId" class="form-control" asp-items="@(new SelectList(Model.TypeCruises, "TypeCruiseId", "Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cruise.Boat" class="form-label"></label>
                <select asp-for="BoatId" class="form-control" asp-items="@(new SelectList(Model.Boats, "BoatId", "Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cruise.DateDepart" class="form-label"></label>
                <input asp-for="Cruise.DateDepart" class="form-control" />
                <span asp-validation-for="Cruise.DateDepart" class="text-danger"></span>
                <select asp-for="DeparturePortId" class="form-control" onchange="askDistance()" asp-items="@(new SelectList(Model.Ports, "PortId", "Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cruise.DateArrivee" class="form-label"></label>
                <input asp-for="Cruise.DateArrivee" class="form-control" />
                <span asp-validation-for="Cruise.DateArrivee" class="text-danger"></span>
                <select asp-for="ArrivalPortId" class="form-control" onchange="askDistance()" asp-items="@(new SelectList(Model.Ports, "PortId", "Name"))"></select>
            </div>

            <div class="form-group">
                <label asp-for="Cruise.TransitPorts" class="form-label"></label>
                <select id="transitsPortsSelect" class="form-control" asp-items="@(new SelectList(Model.Ports, "PortId", "Name"))"></select>
                <button type="button" class="btn btn-secondary" onclick="addTransits()">Ajouter transit</button>
                <div id="transitsPorts" class="container"></div>
            </div>
            <div class="form-group">
                <label asp-for="Cruise.DistanceTotal" class="form-label"></label>
                <input asp-for="Cruise.DistanceTotal" id="Cruise_DistanceTotal" disabled="disabled" class="form-control" />
                <span asp-validation-for="Cruise.DistanceTotal" class="text-danger"></span>
            </div>
            <div class="form-group">  
                <label asp-for="Cruise.Images" class="form-label"></label>
                <input type="file" class="form-control" id="formFile" asp-for="File" multiple accept="image/*" />
            </div>
            <fieldset class="form-group">
                <legend class="mt-4">Commodités</legend>
                @{
                    foreach (var commodite in Model.Commodites)
                    {
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="@(commodite.CommoditeId)" name="CommoditesIds" value="@(commodite.CommoditeId)" />
                            <label class="form-check-label" for="@(commodite.CommoditeId)">@commodite.Name</label>
                        </div>
                    }
                }
            </fieldset>
            <div class="form-group">
                <input type="submit" id="submit" value="Ajouter" class="btn btn-primary" />
                <input type="reset" value="Réinitialiser" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary btn-sm" asp-controller="Administration" asp-action="Index">Panel Administration</a>
</div>

@section Scripts {
    <script type="text/javascript">
        var i = 0;
        var transit = [];
    </script>

    <environment include="Development">
        <script src="~/js/createCruise.js" ></script>
    </environment>
    <environment exclude="Development">
        <script src="~/mylib/createCruise.min.js"></script>
    </environment>

}

MediterraneanDreamBoats/Medit1/Views/Cruises/Delete.cshtml
@model Medit1.Models.Cruise

@{
    ViewData["Title"] = "Supprimer croisière";
}

<h1>Supprimer croissière</h1>

<h3>Etes-vous de vouloir supprimer cette croisière ?</h3>
<div>
    <hr />
    <div class="container">
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.DateDepart)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.DateDepart)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.DateArrivee)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.DateArrivee)
            </dd>
        </dl>
    </div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CruiseId" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> 
    </form>
</div>

MediterraneanDreamBoats/Medit1/Views/Cruises/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@model Medit1.Models.ViewModels.DetailCruiseViewModel

@{
    ViewData["Title"] = "Detail de la croisire";
}

<h1>Détail</h1>

<div>
    <h4>@Model.Cruise.Name</h4>
    <hr />
    <div class="row">
        <div id="carouselExampleControls" class="carousel col-md-5" data-ride="carousel">
            <div class="carousel-inner">
                @for (int i = 0; i < Model.Cruise.Images.Count; i++)
                {
                    if (i == 0)
                    {
                        <div class="carousel-item active">
                            <img src="~/img/cruises/@Model.Cruise.Images.ElementAt(i).Path" class="d-block w-100" alt="une image d'une croisiere">
                        </div>
                    }
                    else
                    {
                        <div class="carousel-item">
                            <img src="~/img/cruises/@Model.Cruise.Images.ElementAt(i).Path" class="d-block w-100" alt="une image d'une croisiere">
                        </div>
                    }
                }

                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
            </div>
        </div>
        <dl class="col-md-5">
            <dt>
                @Html.DisplayNameFor(model => model.PlaceDisponible)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PlaceDisponible) /
                @Html.DisplayFor(model => model.PlaceTotal)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cruise.DateDepart)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cruise.DateDepart) :
                @Html.DisplayFor(model => model.Cruise.PortDepart.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cruise.DateArrivee)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cruise.DateArrivee) :
                @Html.DisplayFor(model => model.Cruise.ArrivalPort.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cruise.Boat)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cruise.Boat.Type) :
                @Html.DisplayFor(model => model.Cruise.Boat.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cruise.TypeCruise)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cruise.TypeCruise.Name) :
                @Html.DisplayFor(model => model.Cruise.TypeCruise.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cruise.TransitPorts)
            </dt>
            <dd>
                @{
                    var transit = "";
                    foreach (var cruisePort in Model.Cruise.TransitPorts)
                    {
                        transit += cruisePort.Port.Name + " ";
                    }
                    <div>@transit</div>
                }
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cruise.DistanceTotal)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cruise.DistanceTotal)
            </dd>
            <dt >
                @Html.DisplayNameFor(model => model.Cruise.Commodites)
            </dt>
            <dd >
                @{
                    var commodite = "";
                    foreach (var cruiseCommodite in Model.Cruise.Commodites)
                    {
                        commodite += cruiseCommodite.Commodite.Name + "   ";
                    }
                    <div>@commodite</div>
                }
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.Cruise.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cruise.Description)
            </dd>
        </dl>
        <div class="col-md-2">
            @{
                if (Model.Cruise.AdultOnly)
                {
                    <div class="alert alert-danger" role="alert">
                        Réservé aux adultes !
                    </div>
                }
                if (SignInManager.IsSignedIn(User) && Model.PlaceDisponible!=0)
                {
                    <a class="btn btn-primary" type="button" asp-controller="Reservations" asp-action="Create" asp-route-id="@Model.Cruise.CruiseId">Réserver</a>
                }
                @if (User.IsInRole("Director"))
                {
                    <a class="btn btn-secondary" type="button" asp-action="Delete" asp-route-id="@Model.Cruise.CruiseId">Supprimer</a>
                }

            }
        </div>
    </div>

</div>

MediterraneanDreamBoats/Medit1/Views/Cruises/Index.cshtml
@model Medit1.Models.ViewModels.IndexCruiseViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Csrf

@functions
{
    public string GetToken()
    {
        return Csrf.GetAndStoreTokens(Context).RequestToken;
    }
}

<input type="hidden" id="GetToken" name="GetToken" value="@GetToken()" />
@{
    ViewData["Title"] = "Croisières";
}

<h1 class="h1">Toutes les croisières</h1>
<div class="container">
    @{
        if (SignInManager.IsSignedIn(User) && User.IsInRole("Director"))
        {
            <a asp-action="Create" class="btn btn-info">Ajouter une croisière</a>
        }
    }
    <div class="row">
        <div class="dropdown col-sm-4">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="filterButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="False">
                Filter
            </button>
            <div class="dropdown-menu" aria-labelledby="filterButton">
                <a asp-action="Index" asp-route-filterId="-1" class="dropdown-item">Toutes les croisières</a>
                @foreach (var type in Model.TypeCruises)
                {
                    <a asp-action="Index" asp-route-filterId="@type.TypeCruiseId" class="dropdown-item">@type.Name</a>
                }
                <a asp-action="Index" asp-route-filterId="-2" class="dropdown-item">Réservé aux adultes</a>
            </div>
        </div>
        <div class="col-sm-6">
            <form class="form-group " asp-action="Index" method="get">
                <input name="filterId" value="@ViewBag.FilterId" hidden="hidden" />
                <label class="col col-form-label" for="portname">Rechercher selon le port: </label>
                <input class="form-control" type="text" name="portname" id="portname" value="@ViewBag.Portname" />
                <input type="submit" value="Rechercher" class="btn btn-secondary" />
            </form>
        </div>
    </div>

    @foreach (var item in Model.Cruises)
    {

        <div class="row">
            <div class="col-md-4">
                @{
                    if (item.Images.Count != 0)
                    {
                        <a asp-action="Details" asp-route-id="@item.CruiseId"><img src="~/img/cruises/@item.Images.ElementAt(0).Path" width="300" height="150" class="img-fluid rounded mb-3 mb-md-0" alt="une image d'une croisiere"></a>
                    }
                }
            </div>
            <div class="col-md-6">
                <div>Name : @item.Name</div>
                <div>Departure : @item.DateDepart.ToLongDateString() : @item.PortDepart.Name</div>
                <div>Arrival : @item.DateArrivee.ToLongDateString() : @item.ArrivalPort.Name</div>
                @{
                    var transit = new List<string>();
                    foreach (var tran in item.TransitPorts)
                    {
                        transit.Add(tran.Port.Name);
                    }
                    var join = String.Join(", ", transit);
                    if (transit.Count != 0)
                    {
                        <div>Port(s) de transit(s) : @join</div>
                    }
                }
            </div>
            <div class="col-md-2">
                @{
                    if (item.AdultOnly)
                    {
                        <div class="alert alert-danger" role="alert">Réservé aux adultes !</div>
                    }
                }
                <a class="btn btn-info" asp-action="Details" asp-route-id="@item.CruiseId">Voir les détails</a>
            </div>
        </div>
        <hr />
    }
</div>

@section Scripts
{
    <environment include="Development">
        <script src="~/js/cruisesFilter.js" asp-append-version="true"></script>
        <script src="~/jqueryui/jquery-ui.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/jqueryui/jquery-ui.min.js" asp-append-version="true"></script>
        <script src="~/mylib/cruisesFilter.min.js" asp-append-version="true"></script>
    </environment>

}