MediterraneanDreamBoats/Medit1/Controllers/CruisesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Medit1.Models;
using Medit1.Models.ViewModels;
using Medit1.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace Medit1.Controllers
{
    
    public class CruisesController : Controller
    {
        private readonly Medit1DbContext _context;

        public CruisesController(Medit1DbContext context)
        {
            _context = context;
        }

        // GET: Cruises
        public async Task<IActionResult> Index(int filterId =-1,string portname = "")
        {
            ViewBag.Portname = portname;
            ViewBag.FilterId = filterId;
            var viewModels = new IndexCruiseViewModel
            {
                Cruises = new List<Cruise>(),
                TypeCruises = await _context.TypeCruises.ToListAsync()
            };

            var ports = await _context.Ports.ToListAsync();
            IQueryable<Cruise> cruisesQueryable = _context.Cruises
                .Include(c => c.PortDepart)
                .Include(c => c.ArrivalPort)
                .Include(c => c.Boat)
                .Include(c => c.Images)
                .Include(c => c.TransitPorts).ThenInclude(t=>t.Port); 
            if (! string.IsNullOrEmpty(portname))
            {
                cruisesQueryable = cruisesQueryable.Where(c =>
                    c.PortDepart.Name.Contains(portname) ||
                    c.ArrivalPort.Name.Contains(portname) ||
                    c.TransitPorts.Any(t => t.Port.Name.Contains(portname)));
            }

            var cruises = filterId switch
            {
                -1 => await cruisesQueryable.ToListAsync(),
                -2 => await cruisesQueryable.Where(c => c.AdultOnly).ToListAsync(),
                _ => await cruisesQueryable.Where(c => c.TypeCruise.TypeCruiseId == filterId).ToListAsync(),
            };
            foreach (var cruise in from cruise in cruises
                where cruise.DateDepart > DateTime.Now && cruise.DateArrivee > DateTime.Now
                let nbReservation = _context.ParticipantReservations.Include(p => p.Reservation).ThenInclude(p => p.Cruise)
                    .Where(p => p.Reservation.Cruise.CruiseId == cruise.CruiseId).ToList()
                .Count let nbTotalPlace = cruise.Boat.NbConvives let placeDispo = nbTotalPlace - nbReservation where placeDispo > 0 select cruise)
            {
                cruise.DistanceTotal = DistanceCalculator.GetDistance(cruise.PortDepart, cruise.ArrivalPort, cruise.TransitPorts);
                viewModels.Cruises.Add(cruise);
            }


            return View(viewModels);
        }

        // GET: Cruises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cruises = await _context.Cruises
                .FirstOrDefaultAsync(m => m.CruiseId == id);
            if (cruises == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var cruise = await _context.Cruises.Include(c => c.PortDepart)
                .Include(m=>m.ArrivalPort)
                .Include(m=>m.TypeCruise)
                .Include(m=>m.Boat)
                .Include(m=>m.Images)
                .Include(m=>m.Commodites).ThenInclude(co=>co.Commodite)
                .Include(m=>m.TransitPorts).ThenInclude(po=>po.Port)
                .FirstOrDefaultAsync(m=>m.CruiseId == id);
            cruise.DistanceTotal = DistanceCalculator.GetDistance(cruise.PortDepart, cruise.ArrivalPort, cruise.TransitPorts);

            var allReservations = await _context.ParticipantReservations.Include(p => p.Reservation).ThenInclude(p => p.Cruise)
                .Where(p => p.Reservation.Cruise.CruiseId == cruise.CruiseId).ToListAsync();

            var nbReservation = allReservations.Count;
            var nbTotalPlace = cruise.Boat.NbConvives;
            var placeDispo = nbTotalPlace - nbReservation;


            var vm = new DetailCruiseViewModel(){Cruise = cruise,PlaceDisponible = placeDispo, PlaceTotal = nbTotalPlace};
            
            return View(vm);
        }
        [Authorize(Roles = "Director")]
        // GET: Cruises/Create
        public async Task<IActionResult> Create()
        {
            var model = new CreateCruiseViewModel()
            {
                Boats = await _context.Boats.ToListAsync(),
                Ports =await _context.Ports.ToListAsync(),
                TypeCruises =await _context.TypeCruises.ToListAsync(),
                Commodites = await _context.Commodites.ToListAsync()
            };
            return View(model);
        }
        [Authorize(Roles = "Director")]
        // POST: Cruises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCruiseViewModel createCruiseViewModel)
        {
            createCruiseViewModel.Boats = await _context.Boats.ToListAsync();
            createCruiseViewModel.Ports = await _context.Ports.ToListAsync();
            createCruiseViewModel.TypeCruises = await _context.TypeCruises.ToListAsync();
            createCruiseViewModel.Commodites = await _context.Commodites.ToListAsync();

            if (!ModelState.IsValid) return View(createCruiseViewModel);
            var cruise = createCruiseViewModel.Cruise;
            var boat = await _context.Boats.FindAsync(createCruiseViewModel.BoatId);
            var departPort = await _context.Ports.FindAsync(createCruiseViewModel.DeparturePortId);
            var arrivalPort = await _context.Ports.FindAsync(createCruiseViewModel.ArrivalPortId);
            var typeCruise = await _context.TypeCruises.FindAsync(createCruiseViewModel.TypeCruiseId);
            if (boat == null && departPort==null && arrivalPort == null && typeCruise==null) return View(createCruiseViewModel);
            cruise.Boat = boat;
            cruise.PortDepart = departPort;
            cruise.ArrivalPort = arrivalPort;
            cruise.TypeCruise = typeCruise;
            cruise.AdultOnly = typeCruise.AdultOnly;
            _context.Add(cruise);
            await _context.SaveChangesAsync();

            await AddImage(createCruiseViewModel.File, cruise);
            await AddTransitPort(createCruiseViewModel.TransitPortId, cruise);
            await AddCommoditeForCruise(createCruiseViewModel.CommoditesIds, cruise);

            return RedirectToAction("Index", "Administration");
        }

        private async Task AddImage(ICollection<IFormFile> images, Cruise cruise)
        {
            if (images != null && images.Count != 0)
            {
                cruise.Images = new List<Image>();
                foreach (var photoFile in images)
                {
                    var image =await ImageAdder.AddImage(photoFile, cruise);
                    //
                    cruise.Images.Add(image);
                    _context.Add(image);
                    await _context.SaveChangesAsync();
                }
            }
        }

        private async Task AddTransitPort(ICollection<int> transitPortIds, Cruise cruise)
        {
            var transit = new List<CruisePort>();
            if (transitPortIds != null) 
                foreach (var transitPortId in transitPortIds)
                {
                    var port = await _context.Ports.FindAsync(transitPortId);
                    if (port != null)
                    {
                        var cruiseport = new CruisePort() { Cruise = cruise, Port = port };
                        transit.Add(cruiseport);
                        await _context.CruisePorts.AddAsync(cruiseport);
                        await _context.SaveChangesAsync();
                    }
                }
            cruise.TransitPorts = transit;
        }

        private async Task AddCommoditeForCruise(ICollection<int> commoditeIds, Cruise cruise)
        {
            var commodites = new List<CruiseCommodite>();
            if (commoditeIds != null) foreach (var commoditeid in commoditeIds)
            {
                var commodite = await _context.Commodites.FindAsync(commoditeid);
                if (commodite != null)
                {
                    var com = new CruiseCommodite() { Cruise = cruise, Commodite = commodite };
                    commodites.Add(com);
                    await _context.CruiseCommodites.AddAsync(com);
                    await _context.SaveChangesAsync();
                }
            }

            cruise.Commodites = commodites;
        }

        [Produces("application/json")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchPort()
        {
            var term = HttpContext.Request.Query["portname"].ToString();
            var list = await _context.Ports.Where(p => p.Name.Contains(term)).Select(p => p.Name).ToListAsync();
            return Ok(list);
        }

        [Produces("application/json")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AskDistance()
        {
            var portDepartId =int.Parse(HttpContext.Request.Query["portDepartId"].ToString());
            var portArrivalId = int.Parse(HttpContext.Request.Query["portArrivalId"].ToString());
            var portsTransitId = HttpContext.Request.Query["portsTransitId"].ToArray();
            var departPort = await _context.Ports.FindAsync(portDepartId);
            var arrivalPort = await _context.Ports.FindAsync(portArrivalId);
            var transitPort = new List<Port>();
            if (departPort != null && arrivalPort != null)
            {

MediterraneanDreamBoats/Medit1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Medit1.Models;
using Microsoft.EntityFrameworkCore;

namespace Medit1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly Medit1DbContext _context;

        public HomeController(ILogger<HomeController> logger,Medit1DbContext context)
        {
            _context = context;
            _logger = logger;
        }
        [ResponseCache(Duration = 60*60*24, Location = ResponseCacheLocation.Any, NoStore = false)]
        public async Task<IActionResult> Index()
        {
            var port = await _context.Ports.ToListAsync();
            return View(port);
        }


        [ResponseCache(Duration = 60*60*24, Location = ResponseCacheLocation.Any, NoStore = false)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

MediterraneanDreamBoats/Medit1/Views/Home/Index.cshtml
@model IEnumerable<Medit1.Models.Port>
@{
    ViewData["Title"] = "Accueil";
}

<h1>Accueil</h1>


<div class="row m-2">
    <div id="carouselExampleControls" class="carousel col-md-8" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/mylib/home_image1.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/mylib/home_image2.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/mylib/home_image3.jpg" class="d-block w-100" alt="...">
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
        </div>
    </div>
    <div class="col-md-3 border-dark offset-1">
        <h2 class="text-center">Heure d'ouverture</h2>
        <ul class="list-unstyled">
            <li>Lundi <span class="float-end">8:00-18:00</span></li>
            <li>Mardi <span class="float-end">9:00-18:00</span></li>
            <li>Mercredi <span class="float-end">8:00-18:00</span></li>
            <li>Jeudi <span class="float-end">9:00-15:00</span></li>
            <li>Vendredi <span class="float-end">10:00-12:30</span></li>
            <li>Samedi <span class="float-end">Closed</span></li>
            <li>Dimanche <span class="float-end">Closed</span></li>
            <li>Téléphone <span class="float-end">+32415445778</span></li>
            <li>Rue de la nueve 60,</li>
            <li>4000 Liege</li>
        </ul>
    </div>
</div>
<div class="m-2">
    <h2>Qui sommes-nous ?</h2>
    <p class="text-center">    Mediterranean dream boats : 
        Nous sommes une entreprise dont notre but est de vous fournir des aventures inexistantes ailleurs et des découvertes de chaques coins du monde.
        Nous fessions tout cela grâces à nos bâteaux de dernières générations, et biensûr qui sont nettoyées par nos soins afin de vous fournir un confort
        optimal et hygiénique. Pour le moment, nous vous fournissons nos services pour vous faire visiter la Méditérannée mais biensûr nous sommes en plein
        dévéloppement. Grâce à vous, notre flotte s\'aggrandit de plus en plus. Nous ne fournissons pas seulement des croisières, il est possible de réserver
        des tournées en hélicoptères mais pour l'instant ce système n'est pas encore disponible sur notre site, il faudrait nous prendre contact via téléphone.
        Merci à vous! Nous sommes déjà plus de 1000000 comptes inscrits sur notre sites et déjà à notre 180 croisières dans nos bateaux de rêves. <br/> Big give away à la 200 croisières.</p>
    


</div>
<div class="m-2">
    <h2>Nos Destinations</h2>
    @{
        var allPort = "";
        foreach (var port in Model)
        {
            allPort += port.Name+" ";
        }
        <p class="text-center">@allPort</p>
    }
    <a class="btn btn-primary" asp-area="" asp-controller="Cruises" asp-action="Index">Voir toutes nos croissières</a>
</div>